ALTER TABLE user
    ADD COLUMN tour_create TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN tour_publish TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN tour_manage TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN tour_copy TINYINT(1) UNSIGNED NOT NULL DEFAULT 0;
